apiVersion: v1
kind: Service
metadata:
  name: ingress-example-service
  labels:
    app: ingress-example
spec:
  selector:
    app: ingress-example
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
  type: NodePort