#Expose it internally
apiVersion: v1
kind: Service
metadata:
  name: bran-service-internal
  labels:
    application: got
    app: bran
spec:
  selector:
    app: bran
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP

---
#Expose it externally
kind: Service
apiVersion: v1
metadata:
  name: bran-service
  labels:
    application: got
    app: bran
spec:
  selector:
    app: bran
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: bran
  labels:
    app: bran
    application: got
spec:
  replicas: 2
  selector:
    matchLabels:
      app: bran
  template:
    metadata:
      labels:
        app: bran
        application: got
    spec:
      containers:
        - name: bran
          image: bran:v6
          ports:
            - containerPort: 80