apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: bran
  labels:
    app: bran
    application: got
spec:
  replicas: 2
  selector:
    matchLabels:
      app: bran
  template:
    metadata:
      labels:
        app: bran
    spec:
      containers:
      - name: bran
        image: bran:v3
        ports:
        - containerPort: 80
---
#Expose bran to the external world
kind: Service
apiVersion: v1
metadata:
  name: bran-service
  labels:
    application: got
spec:
  selector:
    app: bran
  ports:
  - name: http
    protocol: TCP
    port: 8080
    targetPort: 8080
  type: LoadBalancer