apiVersion: v1
kind: Pod
metadata:
  name: configmap-example-pod
  labels:
    app: configmap-example
spec:
  containers:
    - name: configmap-example
      image: configmap-example:v1
      ports:
        - name: nodejs-port
          containerPort: 80
      envFrom:
        - configMapRef:
            name: example-configmap