#Expose it internally
apiVersion: v1
kind: Service
metadata:
  name: hodor
  labels:
    application: got
    app: hodor
spec:
  selector:
    app: hodor
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 8080
  type: ClusterIP

---
#Expose it externally
kind: Service
apiVersion: v1
metadata:
  name: hodor-external
  labels:
    application: got
    app: hodor
spec:
  selector:
    app: hodor
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 8080
  type: LoadBalancer

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: hodor
  labels:
    app: hodor
    application: got
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hodor
  template:
    metadata:
      labels:
        app: hodor
    spec:
      containers:
      - name: hodor
        image: hodor:v3
        ports:
        - containerPort: 80
