apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: hodor
  labels:
    app: hodor
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hodor
  template:
    metadata:
      labels:
        app: hodor
    spec:
      containers:
      - name: hodor
        image: hodor:v1
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: hodor
spec:
  selector:
    app: hodor
  ports:
  - name: http
    protocol: TCP
    port: 8080
    targetPort: 8080