#Expose it internally
apiVersion: v1
kind: Service
metadata:
  name: service-b
  labels:
    application: service-discovery-example
    app: service-b
spec:
  selector:
    app: service-b
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: service-b
  labels:
    app: service-b
    application: service-discovery-example
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-b
  template:
    metadata:
      labels:
        app: service-b
        application: service-discovery-example
    spec:
      containers:
        - name: service-b
          image: service-b:v1
          ports:
            - name: nodejs-port
              containerPort: 80
            - name: http-port
              containerPort: 8080

