apiVersion: settings.k8s.io/v1alpha1
kind: PodPreset
metadata:
  name: share-credential
  labels:
    app: pod-presets-example
spec:
  selector:
    matchLabels:
      app: pod-presets-example
  env:
    - name: MY_SECRET
      value: "123456"
  volumeMounts:
    - mountPath: /share
      name: share-volume
  volumes:
    - name: share-volume
      emptyDir: {}
