# 2 pods of the same type

apiVersion: v1
kind: Pod
metadata:
  name: pod-presets-example-pod-1
  labels:
    app: pod-presets-example
spec:
  containers:
    - name: pod-presets-example
      image: pod-presets-example:v1
---
apiVersion: v1
kind: Pod
metadata:
  name: pod-presets-example-pod-2
  labels:
    app: pod-presets-example
spec:
  containers:
    - name: pod-presets-example
      image: pod-presets-example:v1