---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: service-a
  labels:
    app: service-a
    application: service-discovery-example
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-a
  template:
    metadata:
      labels:
        app: service-a
        application: service-discovery-example
    spec:
      containers:
        - name: service-a
          image: service-a:v1